# Generated by Django 2.2.8 on 2020-10-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('PLANNED', 'Планируется'), ('ACTIVE', 'Активная'), ('CONTROL', 'Контроль'), ('COMPLETED', 'Завершена')], max_length=255, null=True, verbose_name='Статус')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Время начало')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Время завершения')),
                ('planned_completion_time', models.DateTimeField(null=True, verbose_name='Планируемое время завершения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('edited_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
                ('observers', models.ManyToManyField(blank=True, related_name='observers', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task_db',
                'ordering': ['-start_time'],
            },
        ),
    ]
