# Generated by Django 2.2.8 on 2020-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201022_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='before_task_status',
            field=models.CharField(choices=[('PLANNED', 'Планируется'), ('ACTIVE', 'Активная'), ('CONTROL', 'Контроль'), ('COMPLETED', 'Завершена')], max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
