# Generated by Django 2.2.8 on 2020-10-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_notificationforuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationForUser',
        ),
    ]
